# Generated by Django 4.0 on 2022-03-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment_cart_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.comment'),
        ),
    ]
