# Generated by Django 4.0 on 2022-03-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_product_comment_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
