# Generated by Django 4.0 on 2022-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_cart_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
