# Generated by Django 4.0 on 2022-04-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_id'),
        ('home', '0023_cart_grandtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='grandTotal',
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
